<!DOCTYPE html>
<html>
<head>
	<title>First-project generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	<link rel="stylesheet" type="text/css" href="sliders/home/engine1/style.css" />
    <script type="text/javascript" src="sliders/home/engine1/jquery.js"></script>
</head>
<body >
	
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div class="row">
		<div id="wowslider-container1" >
    <div class="ws_images"><ul>
        <li><img src="sliders/home/data1/images/banner1.jpg" alt="Formation : Technicien Spécialisé" title="Formation : Technicien Spécialisé" id="wows1_0"/></li>
        <li><a href="http://wowslider.com/vf"><img src="sliders/home/data1/images/banner2.jpg" alt="Formation :Technicien" title="Formation :Technicien" id="wows1_1"/></a>Technicien Spécialisé en dessin de batiment</li>
        <li><img src="sliders/home/data1/images/banner3.jpg" alt="IAM : Institut Architec de Marrakech" title="IAM : Institut Architec de Marrakech" id="wows1_2"/></li>
    </ul></div>
    <div class="ws_bullets"><div>
        <a href="#" title="Formation : Technicien Spécialisé"><img src="sliders/home/data1/tooltips/banner1.jpg" alt="Formation : Technicien Spécialisé"/>1</a>
        <a href="#" title="Formation :Technicien"><img src="sliders/home/data1/tooltips/banner2.jpg" alt="full screen slider"/>2</a>
        <a href="#" title="IAM : Institut Architec de Marrakech"><img src="sliders/home/data1/tooltips/banner3.jpg" alt="IAM : Institut Architec de Marrakech"/>3</a>
    </div></div>
    
    </div>
	</div>
<hr>

<div class="container">
   <!--  <div class="row">
        <div id="slogan">
            <div class="titres">
                <div class="unTitre">
                    <i class="fa fa-leaf fa-5x  icon-set"></i>
                    <span>Se former</span>
                </div>
                <div class="unTitre">
                    <i class="fa fa-paper-plane-o fa-5x  icon-set"></i>
                    <span>PROGRESSER</span>
                </div>
                <div class="unTitre">
                    <i class="fa fa-thumbs-o-up fa-5x  icon-set"></i>
                    <span>S'éPANOUIR</span>
                </div>
            </div>
        </div>
    </div> -->
	<div class="row">
		
		<div class="row main-low-margin text-center">
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body"><i class="fa fa-leaf fa-5x  icon-set"></i></div>
                <h3>SE FORMER</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body">
                <i class="fa fa-paper-plane-o fa-5x  icon-set"></i></div>
                <h3>PROGRESSER</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body"><i class="fa fa-thumbs-o-up fa-5x  icon-set"></i></div>
                <h3>S'EPANOUIR</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="row">
            	
            	<h1 class="message">
            		C'EST DANS <span class="nom">ARCHITEC</span>
            	</h1>
            	
            </div>
            

        </div>
        <div class="row main-low-margin ">

            <div class="col-md-8 col-sm-8">
                <h3 class="titre-home">QUI SOMMES NOUS?</h3>
                <p>
                    L’institut Architec de Marrakech, IAM, est une école de formation privée autorisée par le Ministère de l'emploi et de la formation professionnelle du Maroc. Crée en 2005,Il exerce le leadership de pionnier dans les formations professionnelles à haute valeur ajoutée, assurant une formation de qualité et de développement de compétences.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                     Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                     tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                     quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                     consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                     cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                     proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>

            <div class="col-md-4 col-sm-4 text-center">
                <img class="img-circle" src="css/image/homer.jpg" width="100">
                <h3 >Mr. Laurent BLANC</h3>
                <h4 >Directeur des études</h4>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere...
                        <a  class="btn btn-default btn-xs"
                        >Lire la suite</a>
                </p>
            </div>
        </div>
        <div class="row main-low-margin ">
        	<h3 class="titre-home">NOS FILÈRES</h3>
        	<div class="row">
        	<div class="col-md-5 text-justify">
        		<blockquote>
        			IAM offre une formation professionnelle moderne. Son cursus est resolument orienté BTP et gestion d'entreprise, et conçu pour s'adapter aux besoins et à la réalitéé économique et industirielle de l'entreprise. 
        		</blockquote>
        	</div>
        	</div>

        	 <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail-"  src="css/image/dessin-bat-cof.jpg">
                </div>
                <h3>DESSINATEUR EN BATIMENT</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-danger btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>
             <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail-" src="css/image/coffre-info.jpg" >
                </div>
                <h3>INFOGRAPHIE</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-info btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>
             <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail" src="css/image/food-q-c-750-300-4.jpg" >
                </div>
                <h3>GESTION INFORMATISEE</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-success btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>



        </div>
	</div>
	</div>
	<script type="text/javascript" src="sliders/home/engine1/wowslider.js"></script>
    <script type="text/javascript" src="sliders/home/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>