<!DOCTYPE html>
<html>
<head>
	<title>First-project generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body >
	
	<div class="container">
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div class="row">
		<div id="wowslider-container1">
			<div class="ws_images"><ul>
				<li>
				<img src="data1/images/foodqc7503001.jpg" alt="Les contacts alt" title="Les contacts title" id="wows1_0"/>
					Tout sur les contacts du monde
					<a href="#">Un lien</a>
					après le lien
				</li>
				<li><img src="data1/images/foodqc7503003.jpg" alt="food-q-c-750-300-3" title="food-q-c-750-300-3" id="wows1_1"/></li>
				<li><img src="data1/images/foodqc7503004.jpg" alt="food-q-c-750-300-4" title="food-q-c-750-300-4" id="wows1_2"/></li>
				<li><img src="data1/images/foodqc7503005.jpg" alt="food-q-c-750-300-5" title="food-q-c-750-300-5" id="wows1_3"/></li>
				<li><img src="data1/images/foodqc7503006.jpg" alt="food-q-c-750-300-6" title="food-q-c-750-300-6" id="wows1_4"/></li>
				<li><img src="data1/images/foodqc7503007.jpg" alt="food-q-c-750-300-7" title="food-q-c-750-300-7" id="wows1_5"/></li>
				<li><img src="data1/images/foodqc7503008.jpg" alt="food-q-c-750-300-8" title="food-q-c-750-300-8" id="wows1_6"/></li>
				<li><a href="http://wowslider.com/vf"><img src="data1/images/foodqc7503009.jpg" alt="full screen slider" title="full screen slider" id="wows1_7"/></a></li>
				<li><img src="data1/images/foodqc75030010.jpg" alt="food-q-c-750-300-10" title="food-q-c-750-300-10" id="wows1_8"/></li>
			</ul></div>
			<div class="ws_bullets"><div>
				<a href="#" title="Les contacts"><img src="data1/tooltips/foodqc7503001.jpg" alt="Les contacts du monde"/>1</a>
				<a href="#" title="food-q-c-750-300-3"><img src="data1/tooltips/foodqc7503003.jpg" alt="food-q-c-750-300-3"/>2</a>
				<a href="#" title="food-q-c-750-300-4"><img src="data1/tooltips/foodqc7503004.jpg" alt="food-q-c-750-300-4"/>3</a>
				<a href="#" title="food-q-c-750-300-5"><img src="data1/tooltips/foodqc7503005.jpg" alt="food-q-c-750-300-5"/>4</a>
				<a href="#" title="food-q-c-750-300-6"><img src="data1/tooltips/foodqc7503006.jpg" alt="food-q-c-750-300-6"/>5</a>
				<a href="#" title="food-q-c-750-300-7"><img src="data1/tooltips/foodqc7503007.jpg" alt="food-q-c-750-300-7"/>6</a>
				<a href="#" title="food-q-c-750-300-8"><img src="data1/tooltips/foodqc7503008.jpg" alt="food-q-c-750-300-8"/>7</a>
				<a href="#" title="full screen slider"><img src="data1/tooltips/foodqc7503009.jpg" alt="full screen slider"/>8</a>
				<a href="#" title="food-q-c-750-300-10"><img src="data1/tooltips/foodqc75030010.jpg" alt="food-q-c-750-300-10"/>9</a>
			</div></div>
			<div class="ws_shadow"></div>
		</div>	
	</div>
<hr>
	<div class="row">
		 <div class="myTimeline">
			
			<h1 class='padd'>Architec </h1>
			<ul class='timeline'>
			  <li class="year first">
			  	Nos Progammes <br>
			  	<img src="css/image/logo-bl-transp.png" width="40" />
			  </li> 
			  <li class="year first">2013</li>
			  <li class='event offset-first'>
			    Something amazing happened today, but it's a secret
			  </li>
			  <li class='event' href="#">
			    Timeline.css is <b>dynamic</b>, <b>responsive</b> and optimized to <b>demonstrate events</b> in your life in a <b>simple and clear</b> way
			  </li>
			  <li class="event">
			    <a href="http://christian-fei.com" title="christian fei">
			    made with &lt;3 by <img src="https://s3-eu-west-1.amazonaws.com/cf.img/var/face.svg" alt="christian fei"/>
			    </a>
			  </li>
			  <li class="event">
			  <a href="http://codepen.io/christian-fei/pen/BJily">
			    Open source project on codepen.io
			    <img src="css/image/iam.png" alt=""/>
			  </a>
			  </li>
			  <li class='event'>
			    Look, a sleepy kitten: <br/>
			    <img src="css/image/logo-bl-transp.png" width="80" />
			    <a href='http://ih2.redbubble.net/image.10311838.0354/flat,550x550,075,f.jpg'>
			    &copy; 2014 IAM</a>
			  </li>
			  <li class="year">2012</li>
				<li class="event offset-first">
					<p>To infinity  ... </p>
			    <img class='centered' src="http://upload.wikimedia.org/wikipedia/en/7/75/Buzz-lightyear-toy-story-3-wallpaper.jpg" alt=""/>
					<a href='http://upload.wikimedia.org/wikipedia/en/7/75/Buzz-lightyear-toy-story-3-wallpaper.jpg'>&copy;</a>
				</li>
				<li class="event">
					<p>... and beyond!</p>
			    <img class='centered' src="http://brandstyle.com.br/wp-content/uploads/2012/05/Woody-7.jpg" alt=""/>
					<a href='http://brandstyle.com.br/wp-content/uploads/2012/05/Woody-7.jpg'>&copy;</a>
				</li>
			</ul>

		</div> 
	</div>

	<!-- <div class="row">
		<div class="myTimeline">
			<ul class='timeline'>
  				<li class="year titre">Nos Formation</li>
  				<li ng-repeat="form in formations" class="event">
  					{{form.nom}}
  				</li>
  			</ul>
		</div>
	</div> -->

	<div class="row">
		
		<div class="row main-low-margin text-center">
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body"><i class="fa fa-leaf fa-5x  icon-set"></i></div>
                <h3>SE FORMER</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body">
                <i class="fa fa-paper-plane-o fa-5x  icon-set"></i></div>
                <h3>PROGESSER</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="h-circle-body"><i class="fa fa-thumbs-o-up fa-5x  icon-set"></i></div>
                <h3>S'EPANOUIR</h3>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
            </div>
            <div class="row">
            	
            	<h1 class="message">
            		C'EST DANS <span class="nom">ARCHITEC</span>
            	</h1>
            	
            </div>
            

        </div>
        <div class="row main-low-margin ">

            <div class="col-md-8 col-sm-8">
                <h3 class="titre-home">QUI SOMMES NOUS?</h3>
                <p>
                    L’institut Architec de Marrakech, IAM, est une école de formation privée autorisée par le Ministère de l'emploi et de la formation professionnelle du Maroc. Crée en 2005,Il exerce le leadership de pionnier dans les formations professionnelles à haute valeur ajoutée, assurant une formation de qualité et de développement de compétences.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                     Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                     tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                     quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                     consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                     cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                     proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>

            <div class="col-md-4 col-sm-4 text-center">
                <img class="img-circle" src="css/image/homer.jpg" width="100">
                <h3 >Mr. Laurent BLANC</h3>
                <h4 >Directeur des études</h4>
                <p class="text-justify">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere...
                        <a  class="btn btn-default btn-xs"
                        >Lire la suite</a>
                </p>
            </div>
        </div>
        <div class="row main-low-margin ">
        	<h3 class="titre-home">NOS FILÈRES</h3>
        	<div class="row">
        	<div class="col-md-5 text-justify">
        		<blockquote>
        			IAM offre une formation professionnelle moderne. Son cursus est resolument orienté BTP et gestion d'entreprise, et conçu pour s'adapter aux besoins et à la réalitéé économique et industirielle de l'entreprise. 
        		</blockquote>
        	</div>
        	</div>

        	 <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail-"  src="css/image/dessin-bat-cof.jpg">
                </div>
                <h3>DESSINATEUR EN BATIMENT</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-danger btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>
             <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail-" src="css/image/coffre-info.jpg" >
                </div>
                <h3>INFOGRAPHIE</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-info btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>
             <div class="col-md-4 col-sm-4 text-center">
                <div class="circle-body">
                <img class="img-thumbnail" src="css/image/food-q-c-750-300-4.jpg" >
                </div>
                <h3>GESTION INFORMATISEE</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                         Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                        Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
                </p>
                <a href="#" class="btn btn-success btn-xs">
                <i class="fa-eye fa"></i>
                Voir plus...
                </a>
            </div>



        </div>
	</div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>