<!DOCTYPE html>
<html>
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="sliders/para-visite/engine1/style.css" />
	<script type="text/javascript" src="sliders/para-visite/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#f0f0f0;margin:0">
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="sliders/para-visite/data1/images/businessqc102148010.jpg" alt="business-q-c-1021-480-10" title="business-q-c-1021-480-10" id="wows1_0"/></li>
		<li><a href="http://wowslider.com/vf"><img src="sliders/para-visite/data1/images/businessqc10214801.jpg" alt="full screen slider" title="full screen slider" id="wows1_1"/></a></li>
		<li><img src="sliders/para-visite/data1/images/businessqc10214804.jpg" alt="business-q-c-1021-480-4" title="business-q-c-1021-480-4" id="wows1_2"/></li>
	</ul></div>
	<div class="ws_bullets"><div>
		<a href="#" title="business-q-c-1021-480-10"><img src="sliders/para-visite/data1/tooltips/businessqc102148010.jpg" alt="business-q-c-1021-480-10"/>1</a>
		<a href="#" title="full screen slider"><img src="sliders/para-visite/data1/tooltips/businessqc10214801.jpg" alt="full screen slider"/>2</a>
		<a href="#" title="business-q-c-1021-480-4"><img src="sliders/para-visite/data1/tooltips/businessqc10214804.jpg" alt="business-q-c-1021-480-4"/>3</a>
	</div></div><span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v7.3</span>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="sliders/para-visite/engine1/wowslider.js"></script>
	<script type="text/javascript" src="sliders/para-visite/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>